### ISSUE TITLE
Export submissions

### ISSUE THREAD

**Issue by olimart** [olimart/formtastic#13]
form has_many submissions. Need to be able to export form submissions as csv file.

- change export route to forms#export instead of api/forms#export
- Export submissions as csv file
- Move existing code from api/submissions_controller to service/concern
- Refactor code to ensure:
  - I think I broke the code but it used to work
  - Change syntax (I don't want `_underscore` all over, neither `@_` symbols)
  - header is dynamic, it should match raw data keys
  - include submissions metadata as well
  - include created_at, spam, sequential_id, raw_data (key, value), metadata (key, value)
  - keep in mind that submissions may be different since keys can be set anytime

**Comment by croko** [comment]
Do you want to expand metadata and raw_data fields to row columns or use metadata and raw_data fields as columns?

**Comment by olimart** [comment]
expand metadata and raw_data fields to row columns

**Comment by croko** [comment]
include form_id?

**Comment by olimart** [comment]
no, since it is scoped per form already.

**Comment by olimart** [comment]
- Rename csv file to form.name
- I changed headers order but I could not find how to change row column order to match headers.
  - I'd like to have the following order:
    1. id (sequential_id)
    2. raw_data
    3. export_keys
    4. metadata
- raw_data is empty (before I edited the code)

**Comment by croko** [comment]
run rake bs
