### ISSUE TITLE
Reject params

### ISSUE THREAD

**Issue by olimart** [olimart/formtastic#18]
On submissions#create we need to reject/filter some of the params received such as:
- name="utf8"
- name: authenticity_token
- commit: Save changes

(and any others you can think of)

**Comment by croko** [comment]
in Api SubmissionsController?

**Comment by olimart** [comment]
Well at the model level, but yes when received by the API submissions
controller

Le dimanche 8 février 2015, Gennady <notifications@github.com> a écrit :

> in Api SubmissionsController?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olimart/formtastic/issues/18#issuecomment-73408989>.
>


-- 
Regards,

Olivier SIMART

*(819) 962-1981*
Projectlog <http://getprojectlog.com> | Blog <http://blog.yafoy.com> | Joli
Bento <http://jolibento.com>

**Comment by croko** [comment]
what about change json data? like this 
```json
{data: {"email": "trunghai@gmail.com", "name": "my name here", "address": {"add1": "add1", "add2": "add2", "zipcode": 60000} }}
and look inside data?

**Comment by olimart** [comment]
not sure I get your point.

**Comment by croko** [comment]
change 
 curl -v -H "Content-type: application/json" -X POST -d '{"email": "trunghai@gmail.com", "name": "my name here", "address": {"add1": "add1", "add2": "add2", "zipcode": 60000} }' http://localhost:3026/api/f/905e236f/
to
curl -v -H "Content-type: application/json" -X POST -d 'submission: {{"email": "trunghai@gmail.com", "name": "my name here", "address": {"add1": "add1", "add2": "add2", "zipcode": 60000} }}' http://localhost:3026/api/f/905e236f/

**Comment by olimart** [comment]
no, because user could submit anything.
Also, it does not have to happen 'live' but submission could be edited when received.

**Comment by croko** [comment]
how submission posts?

**Comment by olimart** [comment]
see forms/1/edit#setup

**Comment by croko** [comment]
ok, I thought you get posts from foreign service

**Comment by olimart** [comment]
it's the case but I don't control how people will design their form.

**Comment by croko** [comment]
and users will send form as json?

**Comment by olimart** [comment]
No.
Users create html form but change the action attributes to us. We receive whatever they send. Plain HTML attributes.

**Comment by croko** [comment]
send to api controller (/api/f/905e236f/) as html form, right?

**Comment by olimart** [comment]
yes.

**Comment by croko** [comment]
do you have an idea how to separate button's name? It could be submit, save, update, create etc...

**Comment by olimart** [comment]
I don't but this is rails-specific. Most submit buttons don't have name. Also, maybe by removing 'submit'.

**Comment by croko** [comment]
as I understand this form not only for rails. May be consider expanding form template to form constructor?

**Comment by olimart** [comment]
sure.

**Comment by croko** [comment]
> I don't but this is rails-specific. Most submit buttons don't have name. Also, maybe by removing 'submit'.

Parameters: {"utf8"=>"✓", "email"=>"dfdfdf", "name"=>"hgjhjhg", "url"=>"jhgjgj", "submit"=>"Update Form", "slug"=>"fc78196f"}

instead "submit" may be any word

**Comment by croko** [comment]
```html
<form accept-charset='UTF-8' action='http://localhost:3000/api/f/fc78196f' method="post">
  <input type="hidden" name="utf8" value="✓">
  <input type="email" name="email" placeholder="Your Email">
  <input type="text" name="name" placeholder="Your Name">
  <input type="url" name="url" placeholder="Your Website">
  <input type="submit" name="submit" value="Update Form" class="button button-primary mt2 mb2">
</form>

**Comment by croko** [comment]
may be get list of fields as input and then show html for form?

**Comment by olimart** [comment]
> maybe get list of fields as input and then show html for form?

? What are referring to ? contact page ?

**Comment by croko** [comment]
on setup tab instead of 
Set up and test your form

1. Copy this code to start your form.
<form accept-charset='UTF-8' action='http://localhost:3000/api/f/880ce7b2'>
  <input type="hidden" name="utf8" value="✓">
ask user for field names and then show form's code

**Comment by olimart** [comment]
on setup tab, we can put whatever we want but the idea is not to be too restrictive.

We receive Array of parameters. Hash array. Why not using plain ruby to remove "forbidden" keys like submit, utf8...from the array ?

**Comment by croko** [comment]
I have no idea how exclude 'submit', it may be any word. We could define usually used names, but in fact in this place may be any value...

**Comment by olimart** [comment]
submit is also the key, value could be anything as you say, but just remove key equals to submit

**Comment by croko** [comment]
no. 
```html
<input type="submit" name="submit" value="Update Form" class="button button-primary mt2 mb2">
```html
try to change name='submit' to something else.

Parameters: {"utf8"=>"✓", "email"=>"khkjhkjh", "name"=>"jhkjhkjh", "url"=>"kjhkjhkh", "ahahah"=>"Update Form", "slug"=>"fc78196f"}

**Comment by olimart** [comment]
submit button without name is valid html, right ?

In that case, let's assume users will not add name to submit button. Let's also reject predefined list of words such as submit, create, send...

**Comment by croko** [comment]
ok

**Comment by olimart** [comment]
Not working. Test missing.
![capture d ecran 2015-02-10 a 01 33 03](https://cloud.githubusercontent.com/assets/547754/6122681/2dfc5e8e-b0c5-11e4-948f-87db2e7d4eed.png)

**Comment by croko** [comment]
Filtered words locate in Submission#filter_raw_data, you should add missing words to array
