### ISSUE TITLE
API JSON response broken

### ISSUE THREAD

**Issue by olimart** [olimart/formtastic#22]
Raising error since moving to CsvUtil
Need to add API test

```ruby
> no implicit conversion of String into Array
app/services/csv_processor.rb, line 13
```

**Comment by croko** [comment]
could you post sample data?

**Comment by olimart** [comment]
I simply use the API submissions#index endpoint with Curl command as per http://localhost:3026/forms/1/edit#export

**Comment by croko** [comment]
which brunch?

**Comment by croko** [comment]
fixed, pushed to master
