### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by olimart** [olimart/formtastic#23]
When filling out contact form it renders JSON response instead of redirecting to form.redirect_url || thanks_page

It works fine when using `/test-form` though.

**Comment by olimart** [comment]
I just realized how you fixed it, by specifying `.html`

However html response should be default for create action. It comes before json in the code and html is rails default. Why not picked up then? I want to avoid specifying extension.

Update the 2 tests that I've started. Need to make sure user gets redirected to default or external page.

**Comment by croko** [comment]
we have default format in routes as JSON. I didn't find how to override format from form, format: html not works

**Comment by olimart** [comment]
I see. Then we can remove from the routes and address each action at the controller level.

**Comment by olimart** [comment]
@croko In production I keep being redirected to root url instead of thanks page

App is hosted on [heroku](https://formz.herokuapp.com). Any idea?

**Comment by croko** [comment]
which production url?
